# Generated by Django 4.2.5 on 2023-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
