# Generated by Django 4.2.5 on 2023-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='generic', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
